version: '3.8'

services:
  cache:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password123#@!
      MYSQL_DATABASE: hotel
    ports:
      - "3306:3306"
    volumes:
      - db:/data
volumes:
  cache:
    driver: local
  db:
    driver: local